### ISSUE TITLE
Among us irl

### ISSUE THREAD

**Issue by Snapcicle** [compilekaiten/enmity-Themes-Color-Map#1]
{
	"name": "example",
	"author": "ur_mom#42069",
	"theme_color_map": {
		"KEYBOARD": ["#000000", "#FFFFFF"],
		"BACKGROUND_PRIMARY": ["#000000", "#FFFFFF"],
		"BACKGROUND_SECONDARY": ["#000000", "#FFFFFF"],
		"BACKGROUND_SECONDARY_ALT": ["#000000", "#FFFFFF"],
		"BACKGROUND_TERTIARY": ["#000000", "#FFFFFF"],
		"BACKGROUND_ACCENT": ["#000000", "#FFFFFF"],
		"BACKGROUND_FLOATING": ["#000000", "#FFFFFF"],
		"BACKGROUND_NESTED_FLOATING": ["#000000", "#FFFFFF"],
		"BACKGROUND_MOBILE_PRIMARY": ["#000000", "#FFFFFF"],
		"BACKGROUND_MOBILE_SECONDARY": ["#000000", "#FFFFFF"],
		"BACKGROUND_MODIFIER_ACCENT": ["#000000", "#FFFFFF"],
		"BACKGROUND_MODIFIER_ACTIVE": ["#000000", "#FFFFFF"],
		"BACKGROUND_MODIFIER_SELECTED": ["#000000", "#FFFFFF"],
		"CHANNELS_DEFAULT": ["#000000", "#FFFFFF"],
		"HEADER_PRIMARY": ["#000000", "#FFFFFF"],
		"HEADER_SECONDARY": ["#000000", "#FFFFFF"],
		"INTERACTIVE_ACTIVE": ["#000000", "#FFFFFF"],
		"INTERACTIVE_MUTED": ["#000000", "#FFFFFF"],
		"INTERACTIVE_NORMAL": ["#000000", "#FFFFFF"],
		"TEXT_LINK": ["#000000", "#FFFFFF"],
		"TEXT_MUTED": ["#000000", "#FFFFFF"],
		"TEXT_NORMAL": ["#000000", "#FFFFFF"]
	},
	"colours": {
		"PRIMARY_DARK": "#FFFFFF",
		"PRIMARY_DARK_100": "#FFFFFF",
		"PRIMARY_DARK_300": "#FFFFFF",
		"PRIMARY_DARK_360": "#FFFFFF",
		"PRIMARY_DARK_400": "#FFFFFF",
		"PRIMARY_DARK_500": "#FFFFFF",
		"PRIMARY_DARK_600": "#FFFFFF",
		"PRIMARY_DARK_630": "#FFFFFF",
		"PRIMARY_DARK_700": "#FFFFFF",
		"PRIMARY_DARK_800": "#FFFFFF",
		"BRAND_NEW": "#FFFFFF",
		"WHITE": "#FFFFFF"
	},
	"unsafe_colors": {
		"CHAT_GREY": "#000000"

**Comment by compilekaiten** [comment]
what are you doing
